/**
 * The mobile app's feature directory, rendered by the "More" tab.
 *
 * WHY IT EXISTS. The tab bar holds nine destinations; the app has 231 screens
 * across 24 feature areas. Everything outside those nine was reachable only if
 * some screen happened to link it inline — 131 of 231 screens were not
 * reachable at all. A tab bar cannot hold 24 areas, so the directory lives
 * behind one tab instead.
 *
 * Mirrors the web sidebar's grouping (src/lib/navigation/primary-nav.ts) so the
 * two products describe the same thing the same way.
 *
 * EVERY href IS A SCREEN THAT EXISTS — generated against app/**'s route files
 * and enforced on every run by audit:links.
 */

export interface NavItem {
  label: string;
  href: string;
}

export interface NavGroup {
  label: string;
  /** Ionicons name, resolved by the More screen. */
  icon: string;
  /**
   * Minimum role required to SEE this group. Display-gating only — every
   * admin API enforces its own permission server-side, so hiding the group
   * removes clutter and the hint that an admin surface exists, not access.
   */
  requiresRole?: "admin";
  items: NavItem[];
}

export const PRIMARY_NAV: readonly NavGroup[] = [
  {
    label: "Overview",
    icon: "view-dashboard",
    items: [
      { label: "Activity", href: "/activity" },
      { label: "Analytics", href: "/analytics" },
      { label: "Dashboard", href: "/dashboard" },
      { label: "Insights", href: "/insights" },
      { label: "Notifications", href: "/notifications" },
      { label: "Reports", href: "/reports" },
      { label: "Search", href: "/search" },
      { label: "Credit score", href: "/analytics/credit-score" },
      { label: "Disputes", href: "/analytics/disputes" },
      { label: "Reports", href: "/analytics/reports" },
      { label: "Trends", href: "/analytics/trends" },
      { label: "Analytics", href: "/dashboard/analytics" },
      { label: "Disputes", href: "/dashboard/disputes" },
      { label: "Documents", href: "/dashboard/documents" },
      { label: "Monitoring", href: "/dashboard/monitoring" },
      { label: "Notifications", href: "/dashboard/notifications" },
      { label: "Progress", href: "/dashboard/progress" },
      { label: "Reports", href: "/dashboard/reports" },
      { label: "Settings", href: "/dashboard/settings" },
      { label: "Spending", href: "/dashboard/spending" },
      { label: "Subscriptions", href: "/dashboard/subscriptions" },
      { label: "Vitality", href: "/dashboard/vitality" },
      { label: "Alerts", href: "/insights/alerts" },
      { label: "Nudges", href: "/insights/nudges" },
      { label: "Spending", href: "/insights/spending" },
      { label: "Weekly summary", href: "/insights/weekly-summary" },
      { label: "Comparison", href: "/reports/comparison" },
      { label: "Upload", href: "/reports/upload" },
    ],
  },
  {
    label: "Credit",
    icon: "speedometer",
    items: [
      { label: "Credit", href: "/credit" },
      { label: "Credit builder", href: "/credit-builder" },
      { label: "Credit repair", href: "/credit-repair" },
      { label: "Disputes", href: "/disputes" },
      { label: "Identity", href: "/identity" },
      { label: "Monitoring", href: "/monitoring" },
      { label: "Age", href: "/credit-builder/age" },
      { label: "Authorized user", href: "/credit-builder/authorized-user" },
      { label: "Budget", href: "/credit-builder/budget" },
      { label: "Debt strategy", href: "/credit-builder/debt-strategy" },
      { label: "Freeze", href: "/credit-builder/freeze" },
      { label: "Goals", href: "/credit-builder/goals" },
      { label: "Goodwill", href: "/credit-builder/goodwill" },
      { label: "Identity theft", href: "/credit-builder/identity-theft" },
      { label: "Loan", href: "/credit-builder/loan" },
      { label: "Mix", href: "/credit-builder/mix" },
      { label: "Pay for delete", href: "/credit-builder/pay-for-delete" },
      { label: "Payments", href: "/credit-builder/payments" },
      { label: "Score simulator", href: "/credit-builder/score-simulator" },
      { label: "Secured card", href: "/credit-builder/secured-card" },
      { label: "Simulator", href: "/credit-builder/simulator" },
      { label: "Utilization", href: "/credit-builder/utilization" },
      { label: "Building", href: "/credit-repair/building" },
      { label: "Cards", href: "/credit-repair/cards" },
      { label: "Disputes", href: "/credit-repair/disputes" },
      { label: "Goodwill", href: "/credit-repair/goodwill" },
      { label: "Inquiries", href: "/credit-repair/inquiries" },
      { label: "Negotiate", href: "/credit-repair/negotiate" },
      { label: "Payments", href: "/credit-repair/payments" },
      { label: "Factors", href: "/credit/factors" },
      { label: "History", href: "/credit/history" },
      { label: "Monitoring", href: "/credit/monitoring" },
      { label: "Score detail", href: "/credit/score-detail" },
      { label: "Analytics", href: "/dispute/analytics" },
      { label: "Create", href: "/dispute/create" },
      { label: "New", href: "/dispute/new" },
      { label: "Strategies", href: "/dispute/strategies" },
      { label: "Templates", href: "/dispute/templates" },
      { label: "Use strategy", href: "/dispute/use-strategy" },
      { label: "Use template", href: "/dispute/use-template" },
      { label: "Wizard", href: "/dispute/wizard" },
      { label: "Dark web", href: "/identity/dark-web" },
      { label: "Alerts", href: "/monitoring/alerts" },
      { label: "Bureaus", href: "/monitoring/bureaus" },
      { label: "Settings", href: "/monitoring/settings" },
      { label: "Upload", href: "/credit-builder/reports/upload" },
    ],
  },
  {
    label: "Financial",
    icon: "wallet",
    items: [
      { label: "Budgeting", href: "/budgeting" },
      { label: "Financial", href: "/financial" },
      { label: "Loans", href: "/loans" },
      { label: "Student loans", href: "/student-loans" },
      { label: "Auto save", href: "/budgeting/auto-save" },
      { label: "Bills", href: "/budgeting/bills" },
      { label: "Subscriptions", href: "/budgeting/subscriptions" },
      { label: "Zero based", href: "/budgeting/zero-based" },
      { label: "Accounts", href: "/financial/accounts" },
      { label: "Bills", href: "/financial/bills" },
      { label: "Budgets", href: "/financial/budgets" },
      { label: "Cash flow", href: "/financial/cash-flow" },
      { label: "Create goal", href: "/financial/create-goal" },
      { label: "Debt", href: "/financial/debt" },
      { label: "Goal detail", href: "/financial/goal-detail" },
      { label: "Goals", href: "/financial/goals" },
      { label: "Holdings", href: "/financial/holdings" },
      { label: "Income", href: "/financial/income" },
      { label: "Investments", href: "/financial/investments" },
      { label: "Net worth", href: "/financial/net-worth" },
      { label: "Overview", href: "/financial/overview" },
      { label: "Reports", href: "/financial/reports" },
      { label: "Savings", href: "/financial/savings" },
      { label: "Spending", href: "/financial/spending" },
      { label: "Stock analysis", href: "/financial/stock-analysis" },
      { label: "Transactions", href: "/financial/transactions" },
      { label: "Calculator", href: "/loans/calculator" },
      { label: "Programs", href: "/loans/programs" },
      { label: "Add", href: "/student-loans/add" },
      { label: "Eligibility", href: "/student-loans/eligibility" },
      { label: "Strategies", href: "/student-loans/strategies" },
    ],
  },
  {
    label: "Investing & Trading",
    icon: "trending-up",
    items: [
      { label: "Investments", href: "/investments" },
      { label: "Trading", href: "/trading" },
      { label: "Add holding", href: "/investments/add-holding" },
      { label: "Analytics", href: "/investments/analytics" },
      { label: "Crypto analysis", href: "/investments/crypto-analysis" },
      { label: "Dividends", href: "/investments/dividends" },
      { label: "Holdings", href: "/investments/holdings" },
      { label: "Performance", href: "/investments/performance" },
      { label: "Rebalance", href: "/investments/rebalance" },
      { label: "Research", href: "/investments/research" },
      { label: "Signals", href: "/investments/signals" },
      { label: "Trading", href: "/investments/trading" },
      { label: "Watchlist", href: "/investments/watchlist" },
      { label: "Agents", href: "/trading/agents" },
      { label: "Backtest", href: "/trading/backtest" },
      { label: "Chart", href: "/trading/chart" },
      { label: "History", href: "/trading/history" },
      { label: "Mode status", href: "/trading/mode-status" },
      { label: "Orders", href: "/trading/orders" },
      { label: "Paper", href: "/trading/paper" },
      { label: "Positions", href: "/trading/positions" },
      { label: "Risk", href: "/trading/risk" },
      { label: "Signal detail", href: "/trading/signal-detail" },
      { label: "Signals", href: "/trading/signals" },
      { label: "Strategies", href: "/trading/strategies" },
      { label: "Fundamental", href: "/investments/analyze/fundamental" },
      { label: "Recommendation", href: "/investments/analyze/recommendation" },
      { label: "Sentiment", href: "/investments/analyze/sentiment" },
      { label: "Technical", href: "/investments/analyze/technical" },
    ],
  },
  {
    label: "Tax",
    icon: "receipt",
    items: [
      { label: "Tax", href: "/tax" },
      { label: "Calendar", href: "/tax/calendar" },
      { label: "Deductions", href: "/tax/deductions" },
      { label: "Documents", href: "/tax/documents" },
      { label: "Optimizer", href: "/tax/optimizer" },
      { label: "Scenarios", href: "/tax/scenarios" },
    ],
  },
  {
    label: "Marketplace",
    icon: "storefront",
    items: [
      { label: "Marketplace", href: "/marketplace" },
      { label: "Recommendations", href: "/recommendations" },
      { label: "Analysis", href: "/marketplace/analysis" },
      { label: "Attorneys", href: "/marketplace/attorneys" },
      { label: "Calculators", href: "/marketplace/calculators" },
      { label: "Coaching", href: "/marketplace/coaching" },
      { label: "Community", href: "/marketplace/community" },
      { label: "Consolidation", href: "/marketplace/consolidation" },
      { label: "Education", href: "/marketplace/education" },
      { label: "Monitoring services", href: "/marketplace/monitoring-services" },
      { label: "Secured cards", href: "/marketplace/secured-cards" },
      { label: "Services", href: "/marketplace/services" },
      { label: "Tradelines", href: "/marketplace/tradelines" },
      { label: "Credit cards", href: "/recommendations/credit-cards" },
      { label: "Insights", href: "/recommendations/insights" },
      { label: "Loans", href: "/recommendations/loans" },
    ],
  },
  {
    label: "AI",
    icon: "sparkles",
    items: [
      { label: "Chat", href: "/chat" },
      { label: "Coach", href: "/coach" },
      { label: "Financial intelligence", href: "/financial-intelligence" },
      { label: "Budget", href: "/coach/budget" },
      { label: "Debt strategy", href: "/coach/debt-strategy" },
      { label: "Goal detail", href: "/coach/goal-detail" },
      { label: "Goals", href: "/coach/goals" },
      { label: "Recommendations", href: "/coach/recommendations" },
      { label: "Action plan", href: "/financial-intelligence/action-plan" },
      { label: "Ai coach", href: "/financial-intelligence/ai-coach" },
      { label: "Bill negotiator", href: "/financial-intelligence/bill-negotiator" },
      { label: "Chat", href: "/financial-intelligence/chat" },
      { label: "Debt payoff", href: "/financial-intelligence/debt-payoff" },
      { label: "Goals manager", href: "/financial-intelligence/goals-manager" },
      { label: "Smart budget", href: "/financial-intelligence/smart-budget" },
      { label: "Smart budget enhanced", href: "/financial-intelligence/smart-budget-enhanced" },
      { label: "Spending insights", href: "/financial-intelligence/spending-insights" },
    ],
  },
  {
    label: "Rewards",
    icon: "trophy",
    items: [
      { label: "Rewards", href: "/rewards" },
      { label: "Badges", href: "/rewards/badges" },
      { label: "Leaderboard", href: "/rewards/leaderboard" },
      { label: "Quests", href: "/rewards/quests" },
    ],
  },
  {
    label: "Account",
    icon: "settings",
    items: [
      { label: "Billing", href: "/billing" },
      { label: "Documents", href: "/documents" },
      { label: "Help", href: "/help" },
      { label: "Profile", href: "/profile" },
      { label: "Settings", href: "/settings" },
      { label: "Invoices", href: "/billing/invoices" },
      { label: "Subscription", href: "/billing/subscription" },
      { label: "Contact", href: "/help/contact" },
      { label: "Faq", href: "/help/faq" },
      { label: "Guide detail", href: "/help/guide-detail" },
      { label: "Guides", href: "/help/guides" },
      { label: "Edit", href: "/profile/edit" },
      { label: "Help", href: "/profile/help" },
      { label: "Security", href: "/profile/security" },
      { label: "Settings", href: "/profile/settings" },
      { label: "Subscription", href: "/profile/subscription" },
      { label: "Billing", href: "/settings/billing" },
      { label: "Connected accounts", href: "/settings/connected-accounts" },
      { label: "Credits", href: "/settings/credits" },
      { label: "Notification preferences", href: "/settings/notification-preferences" },
      { label: "Notifications", href: "/settings/notifications" },
      { label: "Privacy", href: "/settings/privacy" },
      { label: "Profile", href: "/settings/profile" },
      { label: "Transaction rules", href: "/settings/transaction-rules" },
    ],
  },
  {
    label: "Admin",
    icon: "shield-checkmark",
    requiresRole: "admin",
    items: [
      { label: "Admin dashboard", href: "/admin" },
      { label: "Users", href: "/admin/users" },
      { label: "Metrics", href: "/admin/metrics" },
      { label: "Analytics", href: "/admin/analytics" },
      { label: "Disputes", href: "/admin/disputes" },
      { label: "Subscriptions", href: "/admin/subscriptions" },
      { label: "System health", href: "/admin/health" },
      { label: "Logs", href: "/admin/logs" },
      { label: "Audit trail", href: "/admin/audit" },
      { label: "Feature flags", href: "/admin/features" },
      { label: "System config", href: "/admin/config" },
      { label: "Admin settings", href: "/admin/settings" },
    ],
  },
] as const;

export const NAV_HREFS: readonly string[] = PRIMARY_NAV.flatMap((g) =>
  g.items.map((i) => i.href),
);
