/**
 * PCTT Pine Script Generator
 *
 * ============================================================================
 * OPTIONAL FEATURE - NOT REQUIRED FOR TRADING
 * ============================================================================
 *
 * This is an OPTIONAL export utility for users who want to visualize PCTT
 * signals on TradingView. It is NOT required for trading - all trading
 * executes natively through the PCTTTradingService → Broker API path.
 *
 * Use Case: User wants to see PCTT signals on their TradingView charts
 * for visual analysis alongside their Fynvita trading.
 *
 * Primary Trading Path (Native):
 *   Your Charts → PCTTEngine → PCTTTradingService → Alpaca API → Trade
 *
 * Optional Visualization:
 *   Export Pine Script → User pastes into TradingView → View-only signals
 */

import { PCTTConfig, DEFAULT_PCTT_CONFIG } from "./pctt-core";

// ============================================================================
// TYPES
// ============================================================================

export interface PineScriptOptions {
  indicatorName?: string;
  showPivots?: boolean;
  showQScores?: boolean;
  showRegime?: boolean;
  showSignals?: boolean;
  enableAlerts?: boolean;
  alertWebhookUrl?: string;
  alertMessage?: string;
}

const DEFAULT_OPTIONS: PineScriptOptions = {
  indicatorName: "PCTT Structure",
  showPivots: true,
  showQScores: true,
  showRegime: true,
  showSignals: true,
  enableAlerts: true,
};

// ============================================================================
// PINE SCRIPT GENERATOR
// ============================================================================

export function generatePCTTPineScript(
  config: Partial<PCTTConfig> = {},
  options: PineScriptOptions = {},
): string {
  const cfg = { ...DEFAULT_PCTT_CONFIG, ...config };
  const opts = { ...DEFAULT_OPTIONS, ...options };

  return `// ============================================================================
// ${opts.indicatorName} - Pivot-Constrained Trendline Trading
// Generated by Fynvita PCTT Engine
// ============================================================================

//@version=5
indicator("${opts.indicatorName}", overlay=true, max_lines_count=500, max_labels_count=500)

// ============================================================================
// INPUTS
// ============================================================================

// Pivot Detection
i_pivotDepth     = input.int(${cfg.pivotDepth}, "Pivot Depth", minval=2, maxval=20, group="Pivot Detection")
i_pivotLookback  = input.int(${cfg.pivotLookback}, "Pivot Lookback", minval=50, maxval=500, group="Pivot Detection")
i_minPivots      = input.int(${cfg.minPivots}, "Min Pivots for Structure", minval=3, maxval=10, group="Pivot Detection")

// ATR Settings
i_atrPeriod      = input.int(${cfg.atrPeriod}, "ATR Period", minval=5, maxval=50, group="ATR")

// Break/Retest
i_breakPen       = input.float(${cfg.breakPenetration}, "Break Penetration (ATR)", minval=0.05, maxval=1.0, step=0.05, group="Break/Retest")
i_breakConf      = input.float(${cfg.breakConfirmation}, "Break Confirmation (ATR)", minval=0.1, maxval=1.0, step=0.05, group="Break/Retest")
i_retestTol      = input.float(${cfg.retestTolerance}, "Retest Tolerance (ATR)", minval=0.05, maxval=0.5, step=0.05, group="Break/Retest")
i_retestWindow   = input.int(${cfg.retestWindow}, "Retest Window (bars)", minval=5, maxval=50, group="Break/Retest")

// Quality
i_minQScore      = input.float(${cfg.minQScore}, "Min Q-Score", minval=0.5, maxval=0.9, step=0.05, group="Quality")
i_touchTol       = input.float(${cfg.touchTolerance}, "Touch Tolerance (ATR)", minval=0.05, maxval=0.5, step=0.05, group="Quality")

// Regime Detection
i_erPeriod       = input.int(${cfg.erPeriod}, "Efficiency Ratio Period", minval=10, maxval=50, group="Regime")
i_erThreshold    = input.float(${cfg.erTrendThreshold}, "ER Trend Threshold", minval=0.3, maxval=0.7, step=0.05, group="Regime")
i_maxCrossings   = input.int(${cfg.maxCrossings}, "Max Crossings (Range)", minval=2, maxval=10, group="Regime")

// Risk
i_stopBuffer     = input.float(${cfg.stopBuffer}, "Stop Buffer (ATR)", minval=0.1, maxval=2.0, step=0.1, group="Risk")
i_target1R       = input.float(${cfg.target1R}, "Target 1 (R)", minval=0.5, maxval=3.0, step=0.5, group="Risk")
i_target2R       = input.float(${cfg.target2R}, "Target 2 (R)", minval=1.0, maxval=5.0, step=0.5, group="Risk")

// Display
i_showPivots     = input.bool(${opts.showPivots}, "Show Pivots", group="Display")
i_showQScores    = input.bool(${opts.showQScores}, "Show Q-Scores", group="Display")
i_showRegime     = input.bool(${opts.showRegime}, "Show Regime", group="Display")
i_showSignals    = input.bool(${opts.showSignals}, "Show Signals", group="Display")

// Colors
c_support        = input.color(color.new(#26a69a, 0), "Support Color", group="Colors")
c_resistance     = input.color(color.new(#ef5350, 0), "Resistance Color", group="Colors")
c_pivotHigh      = input.color(color.new(#ff9800, 0), "Pivot High Color", group="Colors")
c_pivotLow       = input.color(color.new(#2196f3, 0), "Pivot Low Color", group="Colors")
c_qHigh          = input.color(color.new(#4caf50, 0), "Q High Color", group="Colors")
c_qMed           = input.color(color.new(#ff9800, 0), "Q Medium Color", group="Colors")
c_qLow           = input.color(color.new(#f44336, 0), "Q Low Color", group="Colors")

// ============================================================================
// CALCULATIONS
// ============================================================================

// ATR
atr = ta.atr(i_atrPeriod)

// Confirmed Pivots (non-repainting)
pivotHigh = ta.pivothigh(high, i_pivotDepth, i_pivotDepth)
pivotLow  = ta.pivotlow(low, i_pivotDepth, i_pivotDepth)

// Store pivots
var float[] pivotHighPrices = array.new_float()
var int[]   pivotHighBars   = array.new_int()
var float[] pivotLowPrices  = array.new_float()
var int[]   pivotLowBars    = array.new_int()

if not na(pivotHigh)
    array.push(pivotHighPrices, pivotHigh)
    array.push(pivotHighBars, bar_index - i_pivotDepth)
    if array.size(pivotHighPrices) > i_pivotLookback
        array.shift(pivotHighPrices)
        array.shift(pivotHighBars)

if not na(pivotLow)
    array.push(pivotLowPrices, pivotLow)
    array.push(pivotLowBars, bar_index - i_pivotDepth)
    if array.size(pivotLowPrices) > i_pivotLookback
        array.shift(pivotLowPrices)
        array.shift(pivotLowBars)

// ============================================================================
// BOUNDARY ESTIMATION
// ============================================================================

// Estimate best-fit line from pivots
estimateLine(prices, bars, isSupport) =>
    float bestSlope = 0.0
    float bestIntercept = 0.0
    float bestScore = -999999.0
    int touches = 0
    
    n = array.size(prices)
    if n >= 2
        for i = 0 to math.min(n - 2, 9)
            for j = i + 1 to math.min(n - 1, 10)
                p1 = array.get(prices, i)
                b1 = array.get(bars, i)
                p2 = array.get(prices, j)
                b2 = array.get(bars, j)
                
                if b2 != b1
                    slope = (p2 - p1) / (b2 - b1)
                    intercept = p1 - slope * b1
                    
                    // Count touches
                    touchCount = 0
                    tolerance = i_touchTol * atr
                    for k = 0 to n - 1
                        pk = array.get(prices, k)
                        bk = array.get(bars, k)
                        linePrice = slope * bk + intercept
                        if math.abs(pk - linePrice) <= tolerance
                            touchCount += 1
                    
                    // Score
                    score = touchCount - math.abs(slope) / atr * 0.25
                    
                    if score > bestScore
                        bestScore := score
                        bestSlope := slope
                        bestIntercept := intercept
                        touches := touchCount
    
    [bestSlope, bestIntercept, bestScore, touches]

// Get support line
[supSlope, supIntercept, supScore, supTouches] = estimateLine(pivotLowPrices, pivotLowBars, true)
supQScore = 1.0 / (1.0 + math.exp(-supScore))

// Get resistance line
[resSlope, resIntercept, resScore, resTouches] = estimateLine(pivotHighPrices, pivotHighBars, false)
resQScore = 1.0 / (1.0 + math.exp(-resScore))

// Current line prices
supPrice = supSlope * bar_index + supIntercept
resPrice = resSlope * bar_index + resIntercept

// ============================================================================
// REGIME DETECTION
// ============================================================================

// Efficiency Ratio
priceChange = math.abs(close - close[i_erPeriod])
volatility = math.sum(math.abs(close - close[1]), i_erPeriod)
efficiencyRatio = volatility != 0 ? priceChange / volatility : 0.5

// Crossing count
midline = ta.sma(close, i_erPeriod)
crossing = ta.cross(close, midline)
crossingCount = math.sum(crossing ? 1 : 0, i_erPeriod)

// Regime classification
isTrendUp   = efficiencyRatio >= i_erThreshold and crossingCount <= i_maxCrossings and close > close[i_erPeriod]
isTrendDown = efficiencyRatio >= i_erThreshold and crossingCount <= i_maxCrossings and close < close[i_erPeriod]
isRange     = efficiencyRatio < i_erThreshold * 0.5 or crossingCount > i_maxCrossings * 1.5
isTransition = not isTrendUp and not isTrendDown and not isRange

regime = isTrendUp ? "TREND UP" : isTrendDown ? "TREND DOWN" : isRange ? "RANGE" : "TRANSITION"
regimeColor = isTrendUp ? color.new(#26a69a, 80) : isTrendDown ? color.new(#ef5350, 80) : isRange ? color.new(#9e9e9e, 80) : color.new(#ffeb3b, 90)

// ============================================================================
// EVENT STATE MACHINE
// ============================================================================

var string state = "idle"
var float frozenActionPrice = na
var float frozenSafetyPrice = na
var int breakBar = 0
var string breakDir = ""

// Distance to lines
distToSup = atr != 0 ? (close - supPrice) / atr : 0
distToRes = atr != 0 ? (resPrice - close) / atr : 0

// Check for break
breakUpPen = (high - resPrice) / atr >= i_breakPen
breakUpConf = (close - resPrice) / atr >= i_breakConf
breakDownPen = (supPrice - low) / atr >= i_breakPen
breakDownConf = (supPrice - close) / atr >= i_breakConf

// State transitions
if state == "idle"
    if resQScore >= i_minQScore and breakUpPen and breakUpConf and (isTrendUp or isTransition)
        state := "freeze_up"
        frozenActionPrice := resPrice
        frozenSafetyPrice := supPrice
        breakBar := bar_index
        breakDir := "up"
    else if supQScore >= i_minQScore and breakDownPen and breakDownConf and (isTrendDown or isTransition)
        state := "freeze_down"
        frozenActionPrice := supPrice
        frozenSafetyPrice := resPrice
        breakBar := bar_index
        breakDir := "down"

else if state == "freeze_up"
    barsSinceBreak = bar_index - breakBar
    failureThreshold = frozenSafetyPrice + i_stopBuffer * atr
    
    if close < failureThreshold
        state := "idle"
        frozenActionPrice := na
        frozenSafetyPrice := na
    else if math.abs(low - frozenActionPrice) / atr <= i_retestTol or math.abs(close - frozenActionPrice) / atr <= i_retestTol
        state := "retest_up"
    else if barsSinceBreak > i_retestWindow
        state := "idle"
        frozenActionPrice := na
        frozenSafetyPrice := na

else if state == "freeze_down"
    barsSinceBreak = bar_index - breakBar
    failureThreshold = frozenSafetyPrice - i_stopBuffer * atr
    
    if close > failureThreshold
        state := "idle"
        frozenActionPrice := na
        frozenSafetyPrice := na
    else if math.abs(high - frozenActionPrice) / atr <= i_retestTol or math.abs(close - frozenActionPrice) / atr <= i_retestTol
        state := "retest_down"
    else if barsSinceBreak > i_retestWindow
        state := "idle"
        frozenActionPrice := na
        frozenSafetyPrice := na

else if state == "retest_up"
    rejection = close > frozenActionPrice and low < frozenActionPrice
    if rejection
        state := "entry_long"
    else if close < frozenSafetyPrice
        state := "idle"
        frozenActionPrice := na
        frozenSafetyPrice := na

else if state == "retest_down"
    rejection = close < frozenActionPrice and high > frozenActionPrice
    if rejection
        state := "entry_short"
    else if close > frozenSafetyPrice
        state := "idle"
        frozenActionPrice := na
        frozenSafetyPrice := na

else if state == "entry_long" or state == "entry_short"
    // Reset after entry signal
    state := "idle"
    frozenActionPrice := na
    frozenSafetyPrice := na

// ============================================================================
// SIGNALS
// ============================================================================

longSignal = state == "entry_long"
shortSignal = state == "entry_short"

// Calculate trade levels
longStop = supPrice - i_stopBuffer * atr
longRisk = close - longStop
longTarget1 = close + longRisk * i_target1R
longTarget2 = close + longRisk * i_target2R

shortStop = resPrice + i_stopBuffer * atr
shortRisk = shortStop - close
shortTarget1 = close - shortRisk * i_target1R
shortTarget2 = close - shortRisk * i_target2R

// ============================================================================
// PLOTTING
// ============================================================================

// Support/Resistance Lines
plot(supTouches >= i_minPivots - 2 ? supPrice : na, "Support", c_support, 2, plot.style_line)
plot(resTouches >= i_minPivots - 2 ? resPrice : na, "Resistance", c_resistance, 2, plot.style_line)

// Frozen Lines
plot(not na(frozenActionPrice) ? frozenActionPrice : na, "Frozen Action", color.new(#ffd700, 0), 2, plot.style_linebr)
plot(not na(frozenSafetyPrice) ? frozenSafetyPrice : na, "Frozen Safety", color.new(#9c27b0, 0), 2, plot.style_linebr)

// Regime Background
bgcolor(i_showRegime ? regimeColor : na, title="Regime Background")

// Pivot Markers
plotshape(i_showPivots and not na(pivotHigh) ? pivotHigh : na, "Pivot High", shape.triangledown, location.abovebar, c_pivotHigh, size=size.tiny)
plotshape(i_showPivots and not na(pivotLow) ? pivotLow : na, "Pivot Low", shape.triangleup, location.belowbar, c_pivotLow, size=size.tiny)

// Signal Markers
plotshape(i_showSignals and longSignal, "Long Signal", shape.labelup, location.belowbar, color.new(#26a69a, 0), text="LONG", textcolor=color.white, size=size.normal)
plotshape(i_showSignals and shortSignal, "Short Signal", shape.labeldown, location.abovebar, color.new(#ef5350, 0), text="SHORT", textcolor=color.white, size=size.normal)

// Q-Score Labels
qColor(q) => q >= 0.7 ? c_qHigh : q >= 0.55 ? c_qMed : c_qLow

if i_showQScores and barstate.islast
    if supTouches >= i_minPivots - 2
        label.new(bar_index + 5, supPrice, "Q: " + str.tostring(supQScore * 100, "#.0") + "%", xloc.bar_index, yloc.price, c_support, label.style_label_left, color.white, size.small)
    if resTouches >= i_minPivots - 2
        label.new(bar_index + 5, resPrice, "Q: " + str.tostring(resQScore * 100, "#.0") + "%", xloc.bar_index, yloc.price, c_resistance, label.style_label_left, color.white, size.small)

// ============================================================================
// INFO TABLE
// ============================================================================

var table infoTable = table.new(position.top_right, 2, 6, bgcolor=color.new(#1a1a2e, 10), border_color=color.new(#2d2d44, 0), border_width=1)

if barstate.islast
    table.cell(infoTable, 0, 0, "Regime", text_color=color.gray, text_size=size.small)
    table.cell(infoTable, 1, 0, regime, text_color=isTrendUp ? color.green : isTrendDown ? color.red : color.gray, text_size=size.small)
    
    table.cell(infoTable, 0, 1, "State", text_color=color.gray, text_size=size.small)
    table.cell(infoTable, 1, 1, str.upper(state), text_color=state == "entry_long" ? color.green : state == "entry_short" ? color.red : color.white, text_size=size.small)
    
    table.cell(infoTable, 0, 2, "ER", text_color=color.gray, text_size=size.small)
    table.cell(infoTable, 1, 2, str.tostring(efficiencyRatio * 100, "#.0") + "%", text_color=color.white, text_size=size.small)
    
    table.cell(infoTable, 0, 3, "Sup Q", text_color=color.gray, text_size=size.small)
    table.cell(infoTable, 1, 3, str.tostring(supQScore * 100, "#.0") + "%", text_color=qColor(supQScore), text_size=size.small)
    
    table.cell(infoTable, 0, 4, "Res Q", text_color=color.gray, text_size=size.small)
    table.cell(infoTable, 1, 4, str.tostring(resQScore * 100, "#.0") + "%", text_color=qColor(resQScore), text_size=size.small)
    
    table.cell(infoTable, 0, 5, "ATR", text_color=color.gray, text_size=size.small)
    table.cell(infoTable, 1, 5, str.tostring(atr, "#.##"), text_color=color.white, text_size=size.small)

// ============================================================================
// ALERTS
// ============================================================================

${
  opts.enableAlerts
    ? `
// Long Entry Alert
alertcondition(longSignal, "PCTT Long Entry", "PCTT Long Signal on {{ticker}} at {{close}}")

// Short Entry Alert  
alertcondition(shortSignal, "PCTT Short Entry", "PCTT Short Signal on {{ticker}} at {{close}}")

// Break Alerts
alertcondition(state == "freeze_up", "PCTT Resistance Break", "PCTT Resistance Break on {{ticker}}")
alertcondition(state == "freeze_down", "PCTT Support Break", "PCTT Support Break on {{ticker}}")

// Retest Alerts
alertcondition(state == "retest_up", "PCTT Bullish Retest", "PCTT Bullish Retest on {{ticker}}")
alertcondition(state == "retest_down", "PCTT Bearish Retest", "PCTT Bearish Retest on {{ticker}}")
`
    : "// Alerts disabled"
}

// Webhook Alert with JSON payload
if longSignal
    alert('{"signal":"long","symbol":"' + syminfo.ticker + '","price":' + str.tostring(close) + ',"stop":' + str.tostring(longStop) + ',"target1":' + str.tostring(longTarget1) + ',"target2":' + str.tostring(longTarget2) + ',"qScore":' + str.tostring(resQScore) + ',"regime":"' + regime + '","timestamp":"' + str.tostring(timenow) + '"}', alert.freq_once_per_bar_close)

if shortSignal
    alert('{"signal":"short","symbol":"' + syminfo.ticker + '","price":' + str.tostring(close) + ',"stop":' + str.tostring(shortStop) + ',"target1":' + str.tostring(shortTarget1) + ',"target2":' + str.tostring(shortTarget2) + ',"qScore":' + str.tostring(supQScore) + ',"regime":"' + regime + '","timestamp":"' + str.tostring(timenow) + '"}', alert.freq_once_per_bar_close)
`;
}

// ============================================================================
// EXPORT
// ============================================================================

export default generatePCTTPineScript;
