'use client';

/**
 * Action Plan Manager Component
 *
 * Manage and track personalized financial action plans generated by AI Coach
 */

import { useState, useEffect, useCallback } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/components/ui/Toast';
import { Modal } from '@/components/ui';

interface ActionStep {
  id: string;
  description: string;
  completed: boolean;
  dueDate?: string;
}

interface ActionPlan {
  id: string;
  title: string;
  description: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  category: string;
  estimatedImpact: string;
  timeframe: string;
  steps: ActionStep[];
  completed: boolean;
  progress: number;
  createdAt: string;
  completedAt?: string;
}

export default function ActionPlanManager() {
  const { user } = useAuth();
  const toast = useToast();
  const [loading, setLoading] = useState(true);
  const [actionPlans, setActionPlans] = useState<ActionPlan[]>([]);
  const [selectedPlan, setSelectedPlan] = useState<ActionPlan | null>(null);
  const [filter, setFilter] = useState<'all' | 'active' | 'completed'>('active');

  const fetchActionPlans = useCallback(async () => {
    if (!user) return;

    try {
      setLoading(true);
      const response = await fetch('/api/ai/financial-coach/recommendations');

      if (!response.ok) {
        throw new Error('Failed to fetch action plans');
      }

      interface ApiRecommendation {
        id?: string;
        title: string;
        description: string;
        priority?: 'critical' | 'high' | 'medium' | 'low';
        category?: string;
        impact?: string;
        timeframe?: string;
        steps?: string[];
      }
      const data = await response.json();
      // Transform recommendations into action plans
      const plans: ActionPlan[] = data.recommendations?.map((rec: ApiRecommendation, idx: number) => ({
        id: rec.id || `plan-${idx}`,
        title: rec.title,
        description: rec.description,
        priority: rec.priority || 'medium',
        category: rec.category || 'general',
        estimatedImpact: rec.impact || 'Medium',
        timeframe: rec.timeframe || '1-2 weeks',
        steps: rec.steps?.map((step: string, stepIdx: number) => ({
          id: `step-${idx}-${stepIdx}`,
          description: step,
          completed: false,
        })) || [],
        completed: false,
        progress: 0,
        createdAt: new Date().toISOString(),
      })) || [];

      setActionPlans(plans);
    } catch (_error) {
      // Error logged
      toast.error('Failed to load action plans', 'Please try again later');
    } finally {
      setLoading(false);
    }
  }, [user, toast]);

  useEffect(() => {
    fetchActionPlans();
  }, [fetchActionPlans]);

  const handleToggleStep = async (planId: string, stepId: string) => {
    setActionPlans(prev => prev.map(plan => {
      if (plan.id === planId) {
        const updatedSteps = plan.steps.map(step =>
          step.id === stepId ? { ...step, completed: !step.completed } : step
        );
        const completedSteps = updatedSteps.filter(s => s.completed).length;
        const progress = (completedSteps / updatedSteps.length) * 100;
        const completed = progress === 100;

        return {
          ...plan,
          steps: updatedSteps,
          progress,
          completed,
          completedAt: completed ? new Date().toISOString() : undefined,
        };
      }
      return plan;
    }));

    toast.success('Progress updated', 'Keep up the great work!');
  };

  const handleCompletePlan = async (planId: string) => {
    setActionPlans(prev => prev.map(plan =>
      plan.id === planId
        ? {
            ...plan,
            completed: true,
            progress: 100,
            completedAt: new Date().toISOString(),
            steps: plan.steps.map(s => ({ ...s, completed: true })),
          }
        : plan
    ));

    toast.success('Action plan completed! ', 'Congratulations on your progress!');
    setSelectedPlan(null);
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'critical': return 'bg-red-100 text-red-800 border-red-300';
      case 'high': return 'bg-orange-100 text-orange-800 border-orange-300';
      case 'medium': return 'bg-yellow-100 text-yellow-800 border-yellow-300';
      case 'low': return 'bg-blue-100 text-blue-800 border-blue-300';
      default: return 'bg-gray-100 dark:bg-slate-800 text-gray-800 dark:text-slate-100 border-gray-300 dark:border-slate-600';
    }
  };

  const getPriorityBadgeColor = (priority: string) => {
    switch (priority) {
      case 'critical': return 'bg-red-500';
      case 'high': return 'bg-orange-500';
      case 'medium': return 'bg-yellow-500';
      case 'low': return 'bg-blue-500';
      default: return 'bg-gray-500';
    }
  };

  const filteredPlans = actionPlans.filter(plan => {
    if (filter === 'active') return !plan.completed;
    if (filter === 'completed') return plan.completed;
    return true;
  });

  if (loading) {
    return (
      <div className="space-y-6 animate-pulse">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1, 2, 3].map((i) => (
            <div key={i} className="bg-gray-200 dark:bg-slate-700 rounded-lg h-64" />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Filter Tabs */}
      <div className="flex items-center justify-between">
        <div className="flex space-x-2">
          <button
            onClick={() => setFilter('all')}
            className={`px-4 py-2 rounded-lg font-medium transition-colors ${ filter === 'all' ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 dark:text-slate-200 hover:bg-gray-50 dark:hover:bg-slate-700 dark:bg-slate-900 border border-gray-300 dark:border-slate-600' }`}
          >
            All Plans ({actionPlans.length})
          </button>
          <button
            onClick={() => setFilter('active')}
            className={`px-4 py-2 rounded-lg font-medium transition-colors ${ filter === 'active' ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 dark:text-slate-200 hover:bg-gray-50 dark:hover:bg-slate-700 dark:bg-slate-900 border border-gray-300 dark:border-slate-600' }`}
          >
            Active ({actionPlans.filter(p => !p.completed).length})
          </button>
          <button
            onClick={() => setFilter('completed')}
            className={`px-4 py-2 rounded-lg font-medium transition-colors ${ filter === 'completed' ? 'bg-blue-600 text-white' : 'bg-white text-gray-700 dark:text-slate-200 hover:bg-gray-50 dark:hover:bg-slate-700 dark:bg-slate-900 border border-gray-300 dark:border-slate-600' }`}
          >
            Completed ({actionPlans.filter(p => p.completed).length})
          </button>
        </div>
      </div>

      {/* Action Plans Grid */}
      {filteredPlans.length === 0 ? (
        <div className="text-center py-12 bg-white dark:bg-slate-800 rounded-lg shadow">
          <svg className="mx-auto h-12 w-12 text-gray-400 dark:text-slate-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
          </svg>
          <h3 className="mt-2 text-sm font-medium text-gray-900 dark:text-white">No action plans</h3>
          <p className="mt-1 text-sm text-gray-500 dark:text-slate-400">
            {filter === 'completed' ? 'No completed plans yet' : 'Get started by visiting your AI Coach'}
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredPlans.map((plan) => (
            <div
              key={plan.id}
              className={`border-2 rounded-lg p-6 cursor-pointer hover:shadow-lg transition-all ${
                plan.completed ? 'bg-green-50 border-green-200' : 'bg-white dark:bg-slate-800 ' + getPriorityColor(plan.priority).split(' ')[2]
              }`}
              onClick={() => setSelectedPlan(plan)}
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex-1">
                  <div className="flex items-center mb-2">
                    <div className={`w-3 h-3 rounded-full mr-2 ${getPriorityBadgeColor(plan.priority)}`} />
                    <span className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wide">
                      {plan.category}
                    </span>
                  </div>
                  <h3 className="font-bold text-gray-900 dark:text-white text-lg mb-1">{plan.title}</h3>
                </div>
                {plan.completed && (
                  <svg className="w-6 h-6 text-green-500 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                  </svg>
                )}
              </div>

              <p className="text-sm text-gray-600 dark:text-slate-300 mb-4 line-clamp-2">{plan.description}</p>

              <div className="space-y-3">
                <div className="flex items-center justify-between text-xs text-gray-500 dark:text-slate-400">
                  <span>Impact: {plan.estimatedImpact}</span>
                  <span>{plan.timeframe}</span>
                </div>

                <div>
                  <div className="flex items-center justify-between text-xs text-gray-600 dark:text-slate-300 mb-1">
                    <span>Progress</span>
                    <span className="font-semibold">{Math.round(plan.progress)}%</span>
                  </div>
                  <div className="bg-gray-200 dark:bg-slate-700 rounded-full h-2">
                    <div
                      className={`h-2 rounded-full transition-all ${plan.completed ? 'bg-green-500' : 'bg-blue-500'}`}
                      style={{ width: `${plan.progress}%` }}
                    />
                  </div>
                </div>

                <div className="text-xs text-gray-500 dark:text-slate-400">
                  {plan.steps.filter(s => s.completed).length} of {plan.steps.length} steps completed
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Plan Detail Modal */}
      {selectedPlan && (
        <Modal
          isOpen={!!selectedPlan}
          onClose={() => setSelectedPlan(null)}
          title={selectedPlan.title}
        >
          <div className="space-y-6">
            <div className="flex items-center space-x-2">
              <span className={`inline-block px-3 py-1 rounded-full text-xs font-semibold ${getPriorityColor(selectedPlan.priority)}`}>
                {selectedPlan.priority.toUpperCase()}
              </span>
              <span className="text-sm text-gray-500 dark:text-slate-400">{selectedPlan.category}</span>
            </div>

            <p className="text-gray-700 dark:text-slate-200">{selectedPlan.description}</p>

            <div className="grid grid-cols-2 gap-4 py-4 border-y border-gray-200 dark:border-slate-700">
              <div>
                <div className="text-sm text-gray-500 dark:text-slate-400">Estimated Impact</div>
                <div className="font-semibold text-gray-900 dark:text-white">{selectedPlan.estimatedImpact}</div>
              </div>
              <div>
                <div className="text-sm text-gray-500 dark:text-slate-400">Timeframe</div>
                <div className="font-semibold text-gray-900 dark:text-white">{selectedPlan.timeframe}</div>
              </div>
            </div>

            <div>
              <div className="flex items-center justify-between mb-3">
                <h4 className="font-semibold text-gray-900 dark:text-white">Action Steps</h4>
                <span className="text-sm text-gray-500 dark:text-slate-400">
                  {selectedPlan.steps.filter(s => s.completed).length}/{selectedPlan.steps.length} completed
                </span>
              </div>
              <div className="space-y-2">
                {selectedPlan.steps.map((step, idx) => (
                  <div
                    key={step.id}
                    className={`flex items-start p-3 rounded-lg border ${
                      step.completed ? 'bg-green-50 border-green-200' : 'bg-white dark:bg-slate-800 border-gray-200 dark:border-slate-700'
                    }`}
                  >
                    <input
                      type="checkbox"
                      checked={step.completed}
                      onChange={() => handleToggleStep(selectedPlan.id, step.id)}
                      className="mt-1 mr-3 h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 dark:border-slate-600 rounded"
                      disabled={selectedPlan.completed}
                    />
                    <div className="flex-1">
                      <span className={`text-sm ${step.completed ? 'line-through text-gray-500' : 'text-gray-900 dark:text-white'}`}>
                        {idx + 1}. {step.description}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {!selectedPlan.completed && (
              <button
                onClick={() => handleCompletePlan(selectedPlan.id)}
                className="w-full px-4 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors font-semibold"
              >
                Mark Plan as Complete
              </button>
            )}

            {selectedPlan.completed && selectedPlan.completedAt && (
              <div className="bg-green-50 border border-green-200 rounded-lg p-4 text-center">
                <svg className="mx-auto h-8 w-8 text-green-500 mb-2" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                </svg>
                <p className="text-sm font-semibold text-green-900">Plan Completed!</p>
                <p className="text-xs text-green-700 mt-1">
                  {new Date(selectedPlan.completedAt).toLocaleDateString()}
                </p>
              </div>
            )}
          </div>
        </Modal>
      )}
    </div>
  );
}
