name: creditmaster_billing_module
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  http: ^1.2.0
  creditmaster_domain:
    path: ../../domain
dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
