/* eslint-disable */
import * as Router from "expo-router";

export * from "expo-router";

declare module "expo-router" {
  export namespace ExpoRouter {
    export interface __routes<T extends string = string> extends Record<
      string,
      unknown
    > {
      StaticRoutes:
        | `/`
        | `/(auth)`
        | `/(auth)/forgot-password`
        | `/(auth)/login`
        | `/(auth)/register`
        | `/(tabs)`
        | `/(tabs)/`
        | `/(tabs)/credit`
        | `/(tabs)/disputes`
        | `/(tabs)/financial`
        | `/(tabs)/investments`
        | `/(tabs)/loans`
        | `/(tabs)/profile`
        | `/(tabs)/reports`
        | `/(tabs)/student-loans`
        | `/_sitemap`
        | `/activity`
        | `/admin`
        | `/admin/`
        | `/admin/analytics`
        | `/admin/audit`
        | `/admin/config`
        | `/admin/disputes`
        | `/admin/features`
        | `/admin/health`
        | `/admin/logs`
        | `/admin/metrics`
        | `/admin/settings`
        | `/admin/subscriptions`
        | `/admin/users`
        | `/analytics`
        | `/analytics/`
        | `/analytics/credit-score`
        | `/analytics/disputes`
        | `/analytics/reports`
        | `/analytics/trends`
        | `/billing`
        | `/billing/`
        | `/billing/invoices`
        | `/billing/subscription`
        | `/chat`
        | `/coach`
        | `/coach/`
        | `/coach/budget`
        | `/coach/debt-strategy`
        | `/coach/goal-detail`
        | `/coach/goals`
        | `/coach/recommendations`
        | `/credit`
        | `/credit-builder`
        | `/credit-builder/`
        | `/credit-builder/age`
        | `/credit-builder/authorized-user`
        | `/credit-builder/budget`
        | `/credit-builder/debt-strategy`
        | `/credit-builder/freeze`
        | `/credit-builder/goals`
        | `/credit-builder/goodwill`
        | `/credit-builder/identity-theft`
        | `/credit-builder/loan`
        | `/credit-builder/mix`
        | `/credit-builder/pay-for-delete`
        | `/credit-builder/payments`
        | `/credit-builder/reports`
        | `/credit-builder/reports/upload`
        | `/credit-builder/score-simulator`
        | `/credit-builder/secured-card`
        | `/credit-builder/simulator`
        | `/credit-builder/utilization`
        | `/credit-repair`
        | `/credit-repair/`
        | `/credit-repair/building`
        | `/credit-repair/cards`
        | `/credit-repair/disputes`
        | `/credit-repair/goodwill`
        | `/credit-repair/inquiries`
        | `/credit-repair/negotiate`
        | `/credit-repair/payments`
        | `/credit/`
        | `/credit/factors`
        | `/credit/history`
        | `/credit/monitoring`
        | `/credit/score-detail`
        | `/dashboard`
        | `/dashboard/`
        | `/dashboard/analytics`
        | `/dashboard/disputes`
        | `/dashboard/documents`
        | `/dashboard/monitoring`
        | `/dashboard/notifications`
        | `/dashboard/progress`
        | `/dashboard/reports`
        | `/dashboard/settings`
        | `/dashboard/spending`
        | `/dashboard/subscriptions`
        | `/dashboard/vitality`
        | `/dispute/create`
        | `/dispute/strategies`
        | `/dispute/templates`
        | `/dispute/use-strategy`
        | `/dispute/use-template`
        | `/disputes`
        | `/disputes/`
        | `/disputes/analytics`
        | `/disputes/new`
        | `/documents`
        | `/documents/`
        | `/financial`
        | `/financial-intelligence`
        | `/financial-intelligence/`
        | `/financial-intelligence/action-plan`
        | `/financial-intelligence/ai-coach`
        | `/financial-intelligence/bill-negotiator`
        | `/financial-intelligence/chat`
        | `/financial-intelligence/debt-payoff`
        | `/financial-intelligence/goals-manager`
        | `/financial-intelligence/smart-budget`
        | `/financial-intelligence/smart-budget-enhanced`
        | `/financial-intelligence/spending-insights`
        | `/financial/`
        | `/financial/accounts`
        | `/financial/bills`
        | `/financial/budgets`
        | `/financial/cash-flow`
        | `/financial/debt`
        | `/financial/goals`
        | `/financial/holdings`
        | `/financial/income`
        | `/financial/investments`
        | `/financial/net-worth`
        | `/financial/overview`
        | `/financial/reports`
        | `/financial/savings`
        | `/financial/spending`
        | `/financial/stock-analysis`
        | `/financial/transactions`
        | `/forgot-password`
        | `/help`
        | `/help/`
        | `/help/contact`
        | `/help/faq`
        | `/help/guide-detail`
        | `/help/guides`
        | `/identity`
        | `/identity/`
        | `/identity/dark-web`
        | `/insights`
        | `/insights/`
        | `/investments`
        | `/investments/`
        | `/investments/add-holding`
        | `/investments/analytics`
        | `/investments/analyze`
        | `/investments/analyze/fundamental`
        | `/investments/analyze/recommendation`
        | `/investments/analyze/sentiment`
        | `/investments/analyze/technical`
        | `/investments/crypto-analysis`
        | `/investments/holdings`
        | `/investments/signals`
        | `/investments/watchlist`
        | `/loans`
        | `/loans/calculator`
        | `/loans/programs`
        | `/login`
        | `/marketplace`
        | `/marketplace/`
        | `/marketplace/analysis`
        | `/marketplace/attorneys`
        | `/marketplace/calculators`
        | `/marketplace/coaching`
        | `/marketplace/community`
        | `/marketplace/consolidation`
        | `/marketplace/education`
        | `/marketplace/monitoring-services`
        | `/marketplace/secured-cards`
        | `/marketplace/services`
        | `/marketplace/tradelines`
        | `/monitoring`
        | `/monitoring/`
        | `/monitoring/alerts`
        | `/monitoring/bureaus`
        | `/monitoring/settings`
        | `/notifications`
        | `/onboarding`
        | `/onboarding/`
        | `/onboarding/complete`
        | `/onboarding/connect`
        | `/onboarding/goals`
        | `/onboarding/profile`
        | `/profile`
        | `/profile/edit`
        | `/profile/help`
        | `/profile/security`
        | `/profile/settings`
        | `/profile/subscription`
        | `/recommendations`
        | `/recommendations/`
        | `/recommendations/credit-cards`
        | `/recommendations/insights`
        | `/recommendations/loans`
        | `/register`
        | `/reports`
        | `/reports/comparison`
        | `/reports/upload`
        | `/search`
        | `/settings`
        | `/settings/`
        | `/settings/billing`
        | `/settings/connected-accounts`
        | `/settings/notifications`
        | `/settings/privacy`
        | `/settings/profile`
        | `/student-loans`
        | `/student-loans/`
        | `/student-loans/add`
        | `/student-loans/eligibility`
        | `/student-loans/strategies`;
      DynamicRoutes:
        | `/dispute/${Router.SingleRoutePart<T>}`
        | `/disputes/${Router.SingleRoutePart<T>}`
        | `/document/${Router.SingleRoutePart<T>}`
        | `/documents/${Router.SingleRoutePart<T>}`
        | `/investments/analyze/${Router.SingleRoutePart<T>}`
        | `/monitoring/alerts/${Router.SingleRoutePart<T>}`
        | `/reports/${Router.SingleRoutePart<T>}`
        | `/student-loans/${Router.SingleRoutePart<T>}`;
      DynamicRouteTemplate:
        | `/dispute/[id]`
        | `/disputes/[id]`
        | `/document/[id]`
        | `/documents/[id]`
        | `/investments/analyze/[symbol]`
        | `/monitoring/alerts/[id]`
        | `/reports/[id]`
        | `/student-loans/[id]`;
    }
  }
}
