import { metadata } from '../layout';

describe('RootLayout', () => {
  it('should have correct metadata title', () => {
    expect(metadata).toBeDefined();
    expect(metadata.title).toBe('Next.js');
  });

  it('should have correct metadata description', () => {
    expect(metadata.description).toBe('Generated by Next.js');
  });

  it('metadata should be an object', () => {
    expect(typeof metadata).toBe('object');
  });

  it('metadata should have title and description properties', () => {
    expect(metadata).toHaveProperty('title');
    expect(metadata).toHaveProperty('description');
  });
});

